version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: ghGist-blog-mongodb
    ports:
      - "27018:27017"
    environment:
      MONGO_INITDB_DATABASE: ghgistDB
    volumes:
      - mongo_data:/data/db
    networks:
      - ghgist-network
    command: mongod --quiet --logpath /dev/null
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5

  ghgist-blog:
    build: .
    container_name: ghGist-blog 
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
      - MONGODB_URI=mongodb://mongodb:27017/ghgistDB
      - SECRET_KEY=${SECRET_KEY}
    depends_on:
      mongodb:
        condition: service_healthy
    networks:
      - ghgist-network
    restart: on-failure

volumes:
  mongo_data:

networks:
  ghgist-network:
    driver: bridge
