version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: authgo-mongodb
    ports:
      - "27018:27017"
    environment:
      MONGO_INITDB_DATABASE: localDB
    volumes:
      - mongo_data:/data/db
    networks:
      - authgo-network
    command: mongod --quiet --logpath /dev/null
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5

  auth-service:
    build: .
    container_name: ghGist-blog 
    ports:
      - "8080:8080"
    env_file:
      - .env
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/localDB
    depends_on:
      mongodb:
        condition: service_healthy
    networks:
      - authgo-network
    restart: on-failure

volumes:
  mongo_data:

networks:
  authgo-network:
    driver: bridge
